# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/ITMO/1-1/Architecture and hardware description languages/activecore/activecore-master/designs/rtl/udm/syn/NEXYS4_DDR/NEXYS4_DDR.xdc

# IP: ip/sys_clk/sys_clk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_clk || ORIG_REF_NAME==sys_clk} -quiet] -quiet
